export default {
    LITERAL_TEXT:     'LITERAL_TEXT',
    VARIABLE:         'VARIABLE',
    IF_VARIABLE:      'IF_VARIABLE',
    LOGIC_OPERATOR:   'LOGIC_OPERATOR',
    COMPARE_OPERATOR: 'COMPARE_OPERATOR'
};
